"""empty message

Revision ID: 816ec789c67d
Revises: 111f3458b926
Create Date: 2026-03-18 18:21:59.682197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816ec789c67d'
down_revision: Union[str, Sequence[str], None] = '111f3458b926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('links_original_url_key'), 'links', type_='unique')
    op.create_unique_constraint(None, 'links', ['short_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='unique')
    op.create_unique_constraint(op.f('links_original_url_key'), 'links', ['original_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
