"""empty message

Revision ID: 111f3458b926
Revises: 7017bd4bd695
Create Date: 2026-03-18 18:16:12.188385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111f3458b926'
down_revision: Union[str, Sequence[str], None] = '7017bd4bd695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'links', ['original_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='unique')
    # ### end Alembic commands ###
